name: "(WebApi) Build and test on PR"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  check-code-formatting:
    runs-on: ubuntu-latest
    name: Check code formatting against editorconfig

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Check Code Format
        run: dotnet-format --check Invoice_Gen.WebApi.sln

  build:

    needs: [check-code-formatting]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore src/Invoice_Gen.WebApi/Invoice_Gen.WebApi.csproj
      - name: Test
        
        run: dotnet test --no-restore --verbosity normal Invoice_Gen.WebApi.sln
